var test_slider = tns({
	container: '.testimonials-slider',
	controls: false,
	center: 'center',
	loop: true,
	items: 1,
	slideBy: 'page',
	nav: true,
	navContainer: ".navtabs",
	navPosition: "bottom",
	autoplay: false,
	speed: 400,
	autoplayButtonOutput: false,
	mouseDrag: true,
	lazyload: true,
});
